# Generated by Django 5.2.6 on 2025-09-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=10)),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('motivo', models.TextField(help_text='Explica por qué deseas adoptar a esta mascota')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('aceptado', models.BooleanField(default=False)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mascotas.mascota')),
            ],
        ),
    ]
